(async function(){
'use strict';const {SERVICES,COLORS,CFG,esc,dataset,groupBuildings,loadKakao,addMapControls,createMarkerManager,haversine,loadBoundary,renderBoundary,clearOverlays,dataMeta}=GJ;
const all=dataset(),status=document.getElementById('dataStatus'),notice=document.getElementById('mapNotice'),results=document.getElementById('results'),summary=document.getElementById('summary');let map,manager,boundaryPolys=[],selected='all',userPos=null,shown=[],groups=[];
function setNotice(msg,type=''){notice.className='map-notice'+(type?' '+type:'');notice.textContent=msg;}
function fillDongs(){const ds=[...new Set(all.filter(r=>r.권역!=='외부연계').map(r=>r.행정동).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));document.getElementById('dong').innerHTML='<option value="all">전체 행정동</option>'+ds.map(d=>`<option>${esc(d)}</option>`).join('');}
function renderList(){const rows=[...shown];if(userPos)rows.sort((a,b)=>haversine(userPos.lat,userPos.lng,a.위도,a.경도)-haversine(userPos.lat,userPos.lng,b.위도,b.경도));results.innerHTML=rows.slice(0,80).map(r=>{const g=groups.find(x=>x.items.includes(r)),dist=userPos?Math.round(haversine(userPos.lat,userPos.lng,r.위도,r.경도))+'m':'';return `<article class="result" data-key="${esc(g?.key||'')}"><h4>${esc(r.기관명)}</h4><div class="badges">${SERVICES.filter(s=>r[s]).map(s=>`<span class="badge" style="background:${COLORS[s]}">${s}</span>`).join('')}</div><p>${esc(r.주소)}</p><p>${esc(r.이용구분)}${dist?' · '+dist:''}</p></article>`}).join('')||'<div class="status warn">선택 조건에 맞는 기관이 없습니다.</div>';results.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>manager.openGroup(el.dataset.key));}
function render(){if(!map||!manager)return;const q=document.getElementById('search').value.trim().toLowerCase(),usage=document.getElementById('usage').value,dong=document.getElementById('dong').value;shown=all.filter(r=>{if(r.권역==='외부연계'&&usage!=='all')return false;if(usage!=='all'&&r.이용구분!==usage)return false;if(dong!=='all'&&r.행정동!==dong)return false;if(selected!=='all'&&!r[selected])return false;if(q&&!`${r.기관명} ${r.주소} ${r.이용대상} ${r.영역}`.toLowerCase().includes(q))return false;return true});groups=groupBuildings(shown);manager.render(groups,{fit:true});summary.className='status ok';summary.textContent=`표시 기관 ${shown.length}개 · 위치 ${groups.length}곳${groups.filter(g=>g.items.length>1).length?` · 복수기관 건물 ${groups.filter(g=>g.items.length>1).length}곳`:''}`;setNotice(`${selected==='all'?'전체 서비스':selected} 기준 ${shown.length}개 기관을 표시합니다.`);renderList();}
if(!all.length){status.className='status err';status.textContent='기관 데이터가 포함되지 않았습니다. package_builder.html에서 원본 엑셀로 공개용 패키지를 먼저 생성하세요.';setNotice('기관 데이터 파일이 없습니다. 관리자용 패키지 생성이 필요합니다.','err');document.querySelectorAll('input,select,button.svc,#locate,#reset').forEach(x=>x.disabled=true);return;}
try{await loadKakao();const c=CFG.defaultCenter||{lat:37.548,lng:127.082};map=new kakao.maps.Map(document.getElementById('map'),{center:new kakao.maps.LatLng(c.lat,c.lng),level:CFG.defaultLevel||6});addMapControls(map);manager=createMarkerManager(map);status.className='status ok';const meta=dataMeta();status.textContent=`기관 ${all.length}개 자동 로딩 완료${meta.version?' · 기준 '+meta.version:''}`;fillDongs();try{const fc=await loadBoundary();boundaryPolys=renderBoundary(map,fc,{fillOpacity:.035,strokeColor:'#667f91',strokeWeight:1.2})}catch(e){console.warn(e)}render();}
catch(e){status.className='status err';status.textContent=e.message;setNotice(e.message,'err');return;}
document.querySelectorAll('.svc').forEach(b=>b.onclick=()=>{document.querySelectorAll('.svc').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=b.dataset.s;render()});['usage','dong'].forEach(id=>document.getElementById(id).onchange=render);let timer;document.getElementById('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(render,180)};document.getElementById('reset').onclick=()=>{selected='all';document.querySelectorAll('.svc').forEach(x=>x.classList.toggle('active',x.dataset.s==='all'));document.getElementById('search').value='';document.getElementById('usage').value='청소년이용';document.getElementById('dong').value='all';userPos=null;render()};document.getElementById('locate').onclick=()=>{if(!navigator.geolocation){alert('현재 위치 기능을 지원하지 않는 브라우저입니다.');return;}navigator.geolocation.getCurrentPosition(pos=>{userPos={lat:pos.coords.latitude,lng:pos.coords.longitude};map.setCenter(new kakao.maps.LatLng(userPos.lat,userPos.lng));renderList();setNotice('현재 위치 기준 가까운 순으로 목록을 정렬했습니다.');},err=>alert('위치 권한을 확인해주세요: '+err.message),{enableHighAccuracy:true,timeout:10000})};document.getElementById('menu').onclick=()=>document.getElementById('side').classList.toggle('open');
})();
